#!/usr/bin/env node
// Generates packages/shared/src/database.types.ts from a Postgres database, in the
// same shape as `supabase gen types typescript`, without needing Docker.
//
//   npm run db:test            # builds the local "bhojan_test" database
//   npm run db:types           # regenerates the types from it
//
// With the Supabase CLI you can use `supabase gen types typescript --local` instead.
import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const db = process.env.BHOJAN_TEST_DB ?? 'bhojan_test';
const out = resolve(dirname(fileURLToPath(import.meta.url)), '../../packages/shared/src/database.types.ts');

const query = `
with cols as (
  select c.table_name, c.column_name, c.ordinal_position, c.is_nullable = 'YES' as nullable,
         (c.column_default is not null or c.is_identity = 'YES' or c.is_generated = 'ALWAYS') as has_default,
         c.data_type, c.udt_name
  from information_schema.columns c
  join information_schema.tables t on t.table_schema = c.table_schema and t.table_name = c.table_name
  where c.table_schema = 'public' and t.table_type = 'BASE TABLE'
),
fks as (
  select con.conname, rel.relname as table_name, frel.relname as ref_table,
         array(select a.attname from unnest(con.conkey) with ordinality k(n, i) join pg_attribute a on a.attrelid = con.conrelid and a.attnum = k.n order by k.i) as columns,
         array(select a.attname from unnest(con.confkey) with ordinality k(n, i) join pg_attribute a on a.attrelid = con.confrelid and a.attnum = k.n order by k.i) as ref_columns,
         exists (select 1 from pg_index ix where ix.indrelid = con.conrelid and ix.indisunique and ix.indpred is null
                 and (ix.indkey::int2[])::int2[] @> con.conkey and cardinality(ix.indkey::int2[]) = cardinality(con.conkey)) as one_to_one
  from pg_constraint con
  join pg_class rel on rel.oid = con.conrelid
  join pg_class frel on frel.oid = con.confrelid
  join pg_namespace ns on ns.oid = rel.relnamespace
  join pg_namespace fns on fns.oid = frel.relnamespace
  where con.contype = 'f' and ns.nspname = 'public' and fns.nspname = 'public'
),
enums as (
  select t.typname as name, array_agg(e.enumlabel order by e.enumsortorder) as labels
  from pg_type t join pg_enum e on e.enumtypid = t.oid join pg_namespace n on n.oid = t.typnamespace
  where n.nspname = 'public' group by t.typname
),
fns as (
  select p.proname as name, p.pronargdefaults as n_defaults,
         coalesce(p.proargnames, '{}') as arg_names,
         array(select format_type(x, null) from unnest(p.proargtypes::oid[]) x) as arg_types,
         format_type(p.prorettype, null) as return_type, p.proretset as returns_set
  from pg_proc p join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public' and p.prokind = 'f'
    and format_type(p.prorettype, null) <> 'trigger'
    and has_function_privilege('authenticated', p.oid, 'EXECUTE')
)
select json_build_object(
  'columns', (select json_agg(cols order by table_name, ordinal_position) from cols),
  'fks', (select coalesce(json_agg(fks order by table_name, conname), '[]') from fks),
  'enums', (select json_agg(enums order by name) from enums),
  'functions', (select coalesce(json_agg(fns order by name), '[]') from fns)
);`;

const raw = execFileSync('psql', ['-X', '-A', '-t', '-q', '-d', db, '-c', query], { encoding: 'utf8' });
const { columns, fks, enums, functions } = JSON.parse(raw);
const enumNames = new Set(enums.map((e) => e.name));
const tableNames = [...new Set(columns.map((c) => c.table_name))];

function scalar(udt) {
  const name = udt
    .replace(/^_/, '')
    .replace(/^public\./, '')
    .replace(/\[\]$/, '');
  if (enumNames.has(name)) return `Database["public"]["Enums"]["${name}"]`;
  if (
    [
      'int2',
      'int4',
      'int8',
      'float4',
      'float8',
      'numeric',
      'smallint',
      'integer',
      'bigint',
      'double precision',
    ].includes(name)
  )
    return 'number';
  if (['bool', 'boolean'].includes(name)) return 'boolean';
  if (['json', 'jsonb'].includes(name)) return 'Json';
  return 'string';
}
function tsType(udt) {
  const isArray = udt.startsWith('_') || udt.endsWith('[]');
  const base = scalar(udt);
  return isArray ? `${base}[]` : base;
}

const lines = [];
const w = (s = '') => lines.push(s);
w('// Generated by supabase/scripts/gen-types.mjs from the migrations. Do not edit by hand.');
w('export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];');
w();
w('export type Database = {');
w('  public: {');
w('    Tables: {');
for (const table of tableNames) {
  const cols = columns.filter((c) => c.table_name === table);
  w(`      ${table}: {`);
  w('        Row: {');
  for (const c of cols) w(`          ${c.column_name}: ${tsType(c.udt_name)}${c.nullable ? ' | null' : ''};`);
  w('        };');
  w('        Insert: {');
  for (const c of cols)
    w(
      `          ${c.column_name}${c.nullable || c.has_default ? '?' : ''}: ${tsType(c.udt_name)}${c.nullable ? ' | null' : ''};`,
    );
  w('        };');
  w('        Update: {');
  for (const c of cols) w(`          ${c.column_name}?: ${tsType(c.udt_name)}${c.nullable ? ' | null' : ''};`);
  w('        };');
  const rels = fks.filter((f) => f.table_name === table);
  if (!rels.length) {
    w('        Relationships: [];');
  } else {
    w('        Relationships: [');
    for (const r of rels) {
      w('          {');
      w(`            foreignKeyName: "${r.conname}";`);
      w(`            columns: [${r.columns.map((x) => `"${x}"`).join(', ')}];`);
      w(`            isOneToOne: ${r.one_to_one};`);
      w(`            referencedRelation: "${r.ref_table}";`);
      w(`            referencedColumns: [${r.ref_columns.map((x) => `"${x}"`).join(', ')}];`);
      w('          },');
    }
    w('        ];');
  }
  w('      };');
}
w('    };');
w('    Views: { [_ in never]: never };');
w('    Functions: {');
for (const f of functions) {
  const required = f.arg_types.length - f.n_defaults;
  const args = f.arg_types.map((t, i) => `${f.arg_names[i]}${i >= required ? '?' : ''}: ${tsType(t)}`);
  const ret = tableNames.includes(f.return_type.replace(/^public\./, ''))
    ? `Database["public"]["Tables"]["${f.return_type.replace(/^public\./, '')}"]["Row"]`
    : f.return_type === 'void'
      ? 'undefined'
      : tsType(f.return_type);
  w(`      ${f.name}: {`);
  w(`        Args: ${args.length ? `{ ${args.join('; ')} }` : 'never'};`);
  w(`        Returns: ${f.returns_set ? `${ret}[]` : ret};`);
  w('      };');
}
w('    };');
w('    Enums: {');
for (const e of enums) w(`      ${e.name}: ${e.labels.map((l) => `"${l}"`).join(' | ')};`);
w('    };');
w('    CompositeTypes: { [_ in never]: never };');
w('  };');
w('};');
w();
w('type PublicSchema = Database["public"];');
w('export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"];');
w('export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"];');
w('export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"];');
w('export type Enums<T extends keyof PublicSchema["Enums"]> = PublicSchema["Enums"][T];');
w();

writeFileSync(out, lines.join('\n'));
console.log(`Wrote ${out} (${tableNames.length} tables, ${functions.length} functions, ${enums.length} enums)`);
