// Generated by supabase/scripts/gen-types.mjs from the migrations. Do not edit by hand.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      addresses: {
        Row: {
          id: string;
          user_id: string;
          label: string;
          address_line: string;
          locality: string;
          city: string;
          pincode: string | null;
          instructions: string | null;
          latitude: number | null;
          longitude: number | null;
          is_default: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          label?: string;
          address_line: string;
          locality: string;
          city: string;
          pincode?: string | null;
          instructions?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          is_default?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          label?: string;
          address_line?: string;
          locality?: string;
          city?: string;
          pincode?: string | null;
          instructions?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          is_default?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "addresses_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      app_settings: {
        Row: {
          id: boolean;
          payment_mode: Database["public"]["Enums"]["payment_gateway"];
          support_phone: string | null;
          timezone: string;
          updated_at: string;
          delivery_radius_km: number;
        };
        Insert: {
          id?: boolean;
          payment_mode?: Database["public"]["Enums"]["payment_gateway"];
          support_phone?: string | null;
          timezone?: string;
          updated_at?: string;
          delivery_radius_km?: number;
        };
        Update: {
          id?: boolean;
          payment_mode?: Database["public"]["Enums"]["payment_gateway"];
          support_phone?: string | null;
          timezone?: string;
          updated_at?: string;
          delivery_radius_km?: number;
        };
        Relationships: [];
      };
      delivery_slots: {
        Row: {
          id: string;
          provider_id: string;
          meal_type: Database["public"]["Enums"]["meal_type"];
          start_time: string;
          end_time: string;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          provider_id: string;
          meal_type: Database["public"]["Enums"]["meal_type"];
          start_time: string;
          end_time: string;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          provider_id?: string;
          meal_type?: Database["public"]["Enums"]["meal_type"];
          start_time?: string;
          end_time?: string;
          is_active?: boolean;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "delivery_slots_provider_id_fkey";
            columns: ["provider_id"];
            isOneToOne: false;
            referencedRelation: "provider_profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      meal_orders: {
        Row: {
          id: string;
          subscription_id: string;
          customer_id: string;
          provider_id: string;
          delivery_address_id: string;
          scheduled_date: string;
          meal_type: Database["public"]["Enums"]["meal_type"];
          window_start: string | null;
          window_end: string | null;
          status: Database["public"]["Enums"]["meal_status"];
          status_updated_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          subscription_id: string;
          customer_id: string;
          provider_id: string;
          delivery_address_id: string;
          scheduled_date: string;
          meal_type: Database["public"]["Enums"]["meal_type"];
          window_start?: string | null;
          window_end?: string | null;
          status?: Database["public"]["Enums"]["meal_status"];
          status_updated_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          subscription_id?: string;
          customer_id?: string;
          provider_id?: string;
          delivery_address_id?: string;
          scheduled_date?: string;
          meal_type?: Database["public"]["Enums"]["meal_type"];
          window_start?: string | null;
          window_end?: string | null;
          status?: Database["public"]["Enums"]["meal_status"];
          status_updated_at?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "meal_orders_customer_id_fkey";
            columns: ["customer_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "meal_orders_delivery_address_id_fkey";
            columns: ["delivery_address_id"];
            isOneToOne: false;
            referencedRelation: "addresses";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "meal_orders_provider_id_fkey";
            columns: ["provider_id"];
            isOneToOne: false;
            referencedRelation: "provider_profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "meal_orders_subscription_id_fkey";
            columns: ["subscription_id"];
            isOneToOne: false;
            referencedRelation: "subscriptions";
            referencedColumns: ["id"];
          },
        ];
      };
      menu_files: {
        Row: {
          id: string;
          provider_id: string;
          storage_path: string;
          public_url: string;
          file_name: string;
          mime_type: string;
          size_bytes: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          provider_id: string;
          storage_path: string;
          public_url: string;
          file_name: string;
          mime_type: string;
          size_bytes?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          provider_id?: string;
          storage_path?: string;
          public_url?: string;
          file_name?: string;
          mime_type?: string;
          size_bytes?: number | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "menu_files_provider_id_fkey";
            columns: ["provider_id"];
            isOneToOne: false;
            referencedRelation: "provider_profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      menu_items: {
        Row: {
          id: string;
          menu_id: string;
          provider_id: string;
          name: string;
          description: string | null;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          menu_id: string;
          provider_id: string;
          name: string;
          description?: string | null;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          menu_id?: string;
          provider_id?: string;
          name?: string;
          description?: string | null;
          sort_order?: number;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "menu_items_menu_fk";
            columns: ["menu_id", "provider_id"];
            isOneToOne: false;
            referencedRelation: "menus";
            referencedColumns: ["id", "provider_id"];
          },
        ];
      };
      menus: {
        Row: {
          id: string;
          provider_id: string;
          meal_type: Database["public"]["Enums"]["meal_type"];
          day_of_week: number | null;
          menu_date: string | null;
          title: string | null;
          description: string | null;
          image_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          provider_id: string;
          meal_type?: Database["public"]["Enums"]["meal_type"];
          day_of_week?: number | null;
          menu_date?: string | null;
          title?: string | null;
          description?: string | null;
          image_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          provider_id?: string;
          meal_type?: Database["public"]["Enums"]["meal_type"];
          day_of_week?: number | null;
          menu_date?: string | null;
          title?: string | null;
          description?: string | null;
          image_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "menus_provider_id_fkey";
            columns: ["provider_id"];
            isOneToOne: false;
            referencedRelation: "provider_profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      payments: {
        Row: {
          id: string;
          user_id: string;
          subscription_id: string;
          amount_paise: number;
          currency: string;
          status: Database["public"]["Enums"]["payment_status"];
          gateway: Database["public"]["Enums"]["payment_gateway"];
          gateway_order_id: string | null;
          gateway_payment_id: string | null;
          failure_reason: string | null;
          paid_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          subscription_id: string;
          amount_paise: number;
          currency?: string;
          status?: Database["public"]["Enums"]["payment_status"];
          gateway: Database["public"]["Enums"]["payment_gateway"];
          gateway_order_id?: string | null;
          gateway_payment_id?: string | null;
          failure_reason?: string | null;
          paid_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          subscription_id?: string;
          amount_paise?: number;
          currency?: string;
          status?: Database["public"]["Enums"]["payment_status"];
          gateway?: Database["public"]["Enums"]["payment_gateway"];
          gateway_order_id?: string | null;
          gateway_payment_id?: string | null;
          failure_reason?: string | null;
          paid_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "payments_subscription_id_fkey";
            columns: ["subscription_id"];
            isOneToOne: false;
            referencedRelation: "subscriptions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "payments_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      plans: {
        Row: {
          id: string;
          provider_id: string;
          name: string;
          description: string | null;
          plan_type: Database["public"]["Enums"]["plan_type"];
          meal_type: Database["public"]["Enums"]["meal_type"];
          price_rupees: number;
          meals_count: number;
          delivery_days: number[];
          min_notice_days: number;
          is_active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          provider_id: string;
          name: string;
          description?: string | null;
          plan_type: Database["public"]["Enums"]["plan_type"];
          meal_type: Database["public"]["Enums"]["meal_type"];
          price_rupees: number;
          meals_count: number;
          delivery_days: number[];
          min_notice_days?: number;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          provider_id?: string;
          name?: string;
          description?: string | null;
          plan_type?: Database["public"]["Enums"]["plan_type"];
          meal_type?: Database["public"]["Enums"]["meal_type"];
          price_rupees?: number;
          meals_count?: number;
          delivery_days?: number[];
          min_notice_days?: number;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "plans_provider_id_fkey";
            columns: ["provider_id"];
            isOneToOne: false;
            referencedRelation: "provider_profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      provider_locations: {
        Row: {
          provider_id: string;
          latitude: number;
          longitude: number;
          accuracy_m: number | null;
          updated_at: string;
        };
        Insert: {
          provider_id: string;
          latitude: number;
          longitude: number;
          accuracy_m?: number | null;
          updated_at?: string;
        };
        Update: {
          provider_id?: string;
          latitude?: number;
          longitude?: number;
          accuracy_m?: number | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "provider_locations_provider_id_fkey";
            columns: ["provider_id"];
            isOneToOne: true;
            referencedRelation: "provider_profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      provider_profiles: {
        Row: {
          id: string;
          user_id: string;
          business_name: string;
          tagline: string | null;
          description: string | null;
          phone: string;
          diet_type: Database["public"]["Enums"]["diet_type"];
          dietary_options: string[];
          city: string;
          service_areas: string[];
          service_pincodes: string[];
          skip_cutoff_hours: number;
          cover_image_url: string | null;
          rating: number | null;
          rating_count: number;
          is_published: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          business_name: string;
          tagline?: string | null;
          description?: string | null;
          phone: string;
          diet_type?: Database["public"]["Enums"]["diet_type"];
          dietary_options?: string[];
          city: string;
          service_areas?: string[];
          service_pincodes?: string[];
          skip_cutoff_hours?: number;
          cover_image_url?: string | null;
          rating?: number | null;
          rating_count?: number;
          is_published?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          business_name?: string;
          tagline?: string | null;
          description?: string | null;
          phone?: string;
          diet_type?: Database["public"]["Enums"]["diet_type"];
          dietary_options?: string[];
          city?: string;
          service_areas?: string[];
          service_pincodes?: string[];
          skip_cutoff_hours?: number;
          cover_image_url?: string | null;
          rating?: number | null;
          rating_count?: number;
          is_published?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "provider_profiles_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: true;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      subscriptions: {
        Row: {
          id: string;
          customer_id: string;
          provider_id: string;
          plan_id: string;
          delivery_address_id: string;
          delivery_slot_id: string | null;
          status: Database["public"]["Enums"]["subscription_status"];
          plan_name: string;
          plan_type: Database["public"]["Enums"]["plan_type"];
          meal_type: Database["public"]["Enums"]["meal_type"];
          delivery_days: number[];
          meals_total: number;
          price_rupees: number;
          window_start: string | null;
          window_end: string | null;
          start_date: string;
          end_date: string | null;
          activated_at: string | null;
          paused_at: string | null;
          cancelled_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          customer_id: string;
          provider_id: string;
          plan_id: string;
          delivery_address_id: string;
          delivery_slot_id?: string | null;
          status?: Database["public"]["Enums"]["subscription_status"];
          plan_name: string;
          plan_type: Database["public"]["Enums"]["plan_type"];
          meal_type: Database["public"]["Enums"]["meal_type"];
          delivery_days: number[];
          meals_total: number;
          price_rupees: number;
          window_start?: string | null;
          window_end?: string | null;
          start_date: string;
          end_date?: string | null;
          activated_at?: string | null;
          paused_at?: string | null;
          cancelled_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          customer_id?: string;
          provider_id?: string;
          plan_id?: string;
          delivery_address_id?: string;
          delivery_slot_id?: string | null;
          status?: Database["public"]["Enums"]["subscription_status"];
          plan_name?: string;
          plan_type?: Database["public"]["Enums"]["plan_type"];
          meal_type?: Database["public"]["Enums"]["meal_type"];
          delivery_days?: number[];
          meals_total?: number;
          price_rupees?: number;
          window_start?: string | null;
          window_end?: string | null;
          start_date?: string;
          end_date?: string | null;
          activated_at?: string | null;
          paused_at?: string | null;
          cancelled_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "subscriptions_customer_id_fkey";
            columns: ["customer_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "subscriptions_delivery_address_id_fkey";
            columns: ["delivery_address_id"];
            isOneToOne: false;
            referencedRelation: "addresses";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "subscriptions_delivery_slot_id_fkey";
            columns: ["delivery_slot_id"];
            isOneToOne: false;
            referencedRelation: "delivery_slots";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "subscriptions_plan_id_fkey";
            columns: ["plan_id"];
            isOneToOne: false;
            referencedRelation: "plans";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "subscriptions_provider_id_fkey";
            columns: ["provider_id"];
            isOneToOne: false;
            referencedRelation: "provider_profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      users: {
        Row: {
          id: string;
          name: string | null;
          phone: string | null;
          email: string | null;
          role: Database["public"]["Enums"]["user_role"];
          dietary_preferences: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          name?: string | null;
          phone?: string | null;
          email?: string | null;
          role?: Database["public"]["Enums"]["user_role"];
          dietary_preferences?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string | null;
          phone?: string | null;
          email?: string | null;
          role?: Database["public"]["Enums"]["user_role"];
          dietary_preferences?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      app_now: {
        Args: never;
        Returns: string;
      };
      app_today: {
        Args: never;
        Returns: string;
      };
      can_view_provider: {
        Args: { p_provider_id: string };
        Returns: boolean;
      };
      cancel_subscription: {
        Args: { p_subscription_id: string };
        Returns: Database["public"]["Tables"]["subscriptions"]["Row"];
      };
      confirm_test_payment: {
        Args: { p_payment_id: string; p_succeed?: boolean };
        Returns: Database["public"]["Tables"]["subscriptions"]["Row"];
      };
      create_subscription: {
        Args: { p_plan_id: string; p_address_id: string; p_start_date: string; p_slot_id?: string };
        Returns: Database["public"]["Tables"]["payments"]["Row"];
      };
      current_provider_id: {
        Args: never;
        Returns: string;
      };
      delivery_check: {
        Args: { p_provider_id: string; p_address_id: string };
        Returns: string;
      };
      is_address_visible_to_current_provider: {
        Args: { p_address_id: string };
        Returns: boolean;
      };
      is_admin: {
        Args: never;
        Returns: boolean;
      };
      is_customer_of_current_provider: {
        Args: { p_customer_id: string };
        Returns: boolean;
      };
      kitchen_areas: {
        Args: never;
        Returns: { area: string; city: string; kitchens: number }[];
      };
      kitchens_in_area: {
        Args: { p_area: string };
        Returns: { provider_id: string }[];
      };
      kitchens_near: {
        Args: { p_latitude: number; p_longitude: number };
        Returns: { provider_id: string; distance_km: number }[];
      };
      meal_change_deadline: {
        Args: { p_date: string; p_window_start: string; p_cutoff_hours: number };
        Returns: string;
      };
      pause_subscription: {
        Args: { p_subscription_id: string };
        Returns: Database["public"]["Tables"]["subscriptions"]["Row"];
      };
      record_payment_failure: {
        Args: { p_payment_id: string; p_reason?: string };
        Returns: Database["public"]["Tables"]["payments"]["Row"];
      };
      resume_subscription: {
        Args: { p_subscription_id: string; p_resume_date?: string };
        Returns: Database["public"]["Tables"]["subscriptions"]["Row"];
      };
      skip_meal: {
        Args: { p_meal_id: string };
        Returns: Database["public"]["Tables"]["meal_orders"]["Row"];
      };
      unskip_meal: {
        Args: { p_meal_id: string };
        Returns: Database["public"]["Tables"]["meal_orders"]["Row"];
      };
      update_meal_status: {
        Args: { p_meal_ids: string[]; p_status: Database["public"]["Enums"]["meal_status"] };
        Returns: number;
      };
    };
    Enums: {
      diet_type: "VEGETARIAN" | "NON_VEGETARIAN" | "BOTH";
      meal_status: "SCHEDULED" | "PREPARING" | "OUT_FOR_DELIVERY" | "DELIVERED" | "SKIPPED" | "CANCELLED";
      meal_type: "BREAKFAST" | "LUNCH" | "DINNER";
      payment_gateway: "TEST" | "RAZORPAY";
      payment_status: "CREATED" | "PAID" | "FAILED" | "REFUNDED";
      plan_type: "ONE_TIME" | "WEEKLY" | "MONTHLY";
      subscription_status: "PENDING_PAYMENT" | "ACTIVE" | "PAUSED" | "CANCELLED" | "EXPIRED";
      user_role: "CUSTOMER" | "PROVIDER" | "ADMIN";
    };
    CompositeTypes: { [_ in never]: never };
  };
};

type PublicSchema = Database["public"];
export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"];
export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"];
export type Enums<T extends keyof PublicSchema["Enums"]> = PublicSchema["Enums"][T];
